-- Schema-only dump of schema `catalog`, owned by the ingest worker.
-- Generated by `manage.py dump_catalog_contract`; do not edit by hand.
-- The API and the rec engine load this file in their tests.

CREATE SCHEMA catalog;

CREATE TABLE catalog.anime (
    id bigint NOT NULL,
    anilist_id integer NOT NULL,
    mal_id integer,
    shikimori_id text,
    annict_id text,
    format text,
    status text,
    season text,
    season_year integer,
    episodes integer,
    duration_min integer,
    score numeric(3,1),
    popularity integer,
    cover_url text,
    is_adult boolean NOT NULL,
    merge_hash text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE catalog.anime_genre (
    anime_id bigint NOT NULL,
    genre_id bigint NOT NULL
);

ALTER TABLE catalog.anime ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.anime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE catalog.anime_localization (
    locale text NOT NULL,
    title text,
    synopsis text,
    title_source text,
    synopsis_source text,
    title_machine boolean NOT NULL,
    synopsis_machine boolean NOT NULL,
    anime_id bigint NOT NULL,
    CONSTRAINT anime_localization_locale_check CHECK ((locale = ANY (ARRAY['en'::text, 'ru'::text, 'ja'::text, 'ja_latn'::text])))
);

CREATE TABLE catalog.anime_override (
    id bigint NOT NULL,
    field text NOT NULL,
    locale text,
    value text NOT NULL,
    note text NOT NULL,
    updated_by text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    anime_id bigint NOT NULL
);

ALTER TABLE catalog.anime_override ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.anime_override_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE catalog.anime_relation (
    kind text NOT NULL,
    anime_id bigint NOT NULL,
    related_id bigint NOT NULL
);

CREATE TABLE catalog.anime_studio (
    is_main boolean NOT NULL,
    anime_id bigint NOT NULL,
    studio_id bigint NOT NULL
);

CREATE TABLE catalog.anime_synonym (
    id bigint NOT NULL,
    value text NOT NULL,
    locale text,
    anime_id bigint NOT NULL
);

ALTER TABLE catalog.anime_synonym ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.anime_synonym_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE catalog.anime_tag (
    rank smallint NOT NULL,
    is_spoiler boolean NOT NULL,
    anime_id bigint NOT NULL,
    tag_id bigint NOT NULL
);

CREATE TABLE catalog.genre (
    id bigint NOT NULL,
    slug character varying(50) NOT NULL
);

ALTER TABLE catalog.genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE catalog.genre_localization (
    locale text NOT NULL,
    name text NOT NULL,
    genre_id bigint NOT NULL
);

CREATE TABLE catalog.raw_source_record (
    source text NOT NULL,
    source_id text NOT NULL,
    payload jsonb NOT NULL,
    payload_hash text NOT NULL,
    fetched_at timestamp with time zone NOT NULL
);

CREATE TABLE catalog.studio (
    id bigint NOT NULL,
    name text NOT NULL,
    anilist_id integer,
    is_animation_studio boolean NOT NULL
);

ALTER TABLE catalog.studio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.studio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE catalog.tag (
    id bigint NOT NULL,
    slug character varying(100) NOT NULL,
    category text,
    is_spoiler boolean NOT NULL
);

ALTER TABLE catalog.tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE catalog.tag_localization (
    locale text NOT NULL,
    name text NOT NULL,
    tag_id bigint NOT NULL
);

ALTER TABLE ONLY catalog.anime
    ADD CONSTRAINT anime_anilist_id_key UNIQUE (anilist_id);

ALTER TABLE ONLY catalog.anime_genre
    ADD CONSTRAINT anime_genre_pkey PRIMARY KEY (anime_id, genre_id);

ALTER TABLE ONLY catalog.anime_localization
    ADD CONSTRAINT anime_localization_pkey PRIMARY KEY (anime_id, locale);

ALTER TABLE ONLY catalog.anime
    ADD CONSTRAINT anime_mal_id_key UNIQUE (mal_id);

ALTER TABLE ONLY catalog.anime_override
    ADD CONSTRAINT anime_override_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog.anime_override
    ADD CONSTRAINT anime_override_unique UNIQUE NULLS NOT DISTINCT (anime_id, field, locale);

ALTER TABLE ONLY catalog.anime
    ADD CONSTRAINT anime_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog.anime_relation
    ADD CONSTRAINT anime_relation_pkey PRIMARY KEY (anime_id, related_id, kind);

ALTER TABLE ONLY catalog.anime_studio
    ADD CONSTRAINT anime_studio_pkey PRIMARY KEY (anime_id, studio_id);

ALTER TABLE ONLY catalog.anime_synonym
    ADD CONSTRAINT anime_synonym_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog.anime_synonym
    ADD CONSTRAINT anime_synonym_unique UNIQUE (anime_id, value);

ALTER TABLE ONLY catalog.anime_tag
    ADD CONSTRAINT anime_tag_pkey PRIMARY KEY (anime_id, tag_id);

ALTER TABLE ONLY catalog.genre_localization
    ADD CONSTRAINT genre_localization_pkey PRIMARY KEY (genre_id, locale);

ALTER TABLE ONLY catalog.genre
    ADD CONSTRAINT genre_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog.genre
    ADD CONSTRAINT genre_slug_key UNIQUE (slug);

ALTER TABLE ONLY catalog.raw_source_record
    ADD CONSTRAINT raw_source_record_pkey PRIMARY KEY (source, source_id);

ALTER TABLE ONLY catalog.studio
    ADD CONSTRAINT studio_anilist_id_key UNIQUE (anilist_id);

ALTER TABLE ONLY catalog.studio
    ADD CONSTRAINT studio_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog.tag_localization
    ADD CONSTRAINT tag_localization_pkey PRIMARY KEY (tag_id, locale);

ALTER TABLE ONLY catalog.tag
    ADD CONSTRAINT tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY catalog.tag
    ADD CONSTRAINT tag_slug_key UNIQUE (slug);

CREATE INDEX anime_genre_anime_id_ad5b95ba ON catalog.anime_genre USING btree (anime_id);

CREATE INDEX anime_genre_genre_id_484a7a98 ON catalog.anime_genre USING btree (genre_id);

CREATE INDEX anime_localization_anime_id_81a8afac ON catalog.anime_localization USING btree (anime_id);

CREATE INDEX anime_override_anime_id_e5c9b05d ON catalog.anime_override USING btree (anime_id);

CREATE INDEX anime_popularity_idx ON catalog.anime USING btree (popularity DESC);

CREATE INDEX anime_relation_anime_id_a11df1f2 ON catalog.anime_relation USING btree (anime_id);

CREATE INDEX anime_relation_related_id_351e9b5d ON catalog.anime_relation USING btree (related_id);

CREATE INDEX anime_season__365325_idx ON catalog.anime USING btree (season_year);

CREATE INDEX anime_status_390465_idx ON catalog.anime USING btree (status);

CREATE INDEX anime_studio_anime_id_dddb8036 ON catalog.anime_studio USING btree (anime_id);

CREATE INDEX anime_studio_studio_id_eec6a392 ON catalog.anime_studio USING btree (studio_id);

CREATE INDEX anime_synonym_anime_id_156a4ab8 ON catalog.anime_synonym USING btree (anime_id);

CREATE INDEX anime_tag_anime_id_7d9d88ac ON catalog.anime_tag USING btree (anime_id);

CREATE INDEX anime_tag_tag_id_f4dc7b18 ON catalog.anime_tag USING btree (tag_id);

CREATE INDEX genre_localization_genre_id_eb7da4fd ON catalog.genre_localization USING btree (genre_id);

CREATE INDEX genre_slug_b60a9f5e_like ON catalog.genre USING btree (slug varchar_pattern_ops);

CREATE INDEX tag_localization_tag_id_cc88aef6 ON catalog.tag_localization USING btree (tag_id);

CREATE INDEX tag_slug_6044cf44_like ON catalog.tag USING btree (slug varchar_pattern_ops);

ALTER TABLE ONLY catalog.anime_genre
    ADD CONSTRAINT anime_genre_anime_id_ad5b95ba_fk_anime_id FOREIGN KEY (anime_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_genre
    ADD CONSTRAINT anime_genre_genre_id_484a7a98_fk_genre_id FOREIGN KEY (genre_id) REFERENCES catalog.genre(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_localization
    ADD CONSTRAINT anime_localization_anime_id_81a8afac_fk_anime_id FOREIGN KEY (anime_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_override
    ADD CONSTRAINT anime_override_anime_id_e5c9b05d_fk_anime_id FOREIGN KEY (anime_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_relation
    ADD CONSTRAINT anime_relation_anime_id_a11df1f2_fk_anime_id FOREIGN KEY (anime_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_relation
    ADD CONSTRAINT anime_relation_related_id_351e9b5d_fk_anime_id FOREIGN KEY (related_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_studio
    ADD CONSTRAINT anime_studio_anime_id_dddb8036_fk_anime_id FOREIGN KEY (anime_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_studio
    ADD CONSTRAINT anime_studio_studio_id_eec6a392_fk_studio_id FOREIGN KEY (studio_id) REFERENCES catalog.studio(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_synonym
    ADD CONSTRAINT anime_synonym_anime_id_156a4ab8_fk_anime_id FOREIGN KEY (anime_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_tag
    ADD CONSTRAINT anime_tag_anime_id_7d9d88ac_fk_anime_id FOREIGN KEY (anime_id) REFERENCES catalog.anime(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.anime_tag
    ADD CONSTRAINT anime_tag_tag_id_f4dc7b18_fk_tag_id FOREIGN KEY (tag_id) REFERENCES catalog.tag(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.genre_localization
    ADD CONSTRAINT genre_localization_genre_id_eb7da4fd_fk_genre_id FOREIGN KEY (genre_id) REFERENCES catalog.genre(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY catalog.tag_localization
    ADD CONSTRAINT tag_localization_tag_id_cc88aef6_fk_tag_id FOREIGN KEY (tag_id) REFERENCES catalog.tag(id) DEFERRABLE INITIALLY DEFERRED;
