# Generated by Django 5.2.17 on 2026-09-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "db_table": "genre",
            },
        ),
        migrations.CreateModel(
            name="RawSourceRecord",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "source",
                        "source_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.TextField()),
                ("source_id", models.TextField()),
                ("payload", models.JSONField()),
                ("payload_hash", models.TextField()),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "db_table": "raw_source_record",
            },
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("anilist_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("is_animation_studio", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "studio",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("is_spoiler", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tag",
            },
        ),
        migrations.CreateModel(
            name="Anime",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("anilist_id", models.IntegerField(unique=True)),
                ("mal_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("shikimori_id", models.TextField(blank=True, null=True)),
                ("annict_id", models.TextField(blank=True, null=True)),
                ("format", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("FINISHED", "Finished"),
                            ("RELEASING", "Releasing"),
                            ("NOT_YET_RELEASED", "Not Yet Released"),
                            ("CANCELLED", "Cancelled"),
                            ("HIATUS", "Hiatus"),
                            ("REMOVED", "Removed"),
                        ],
                        null=True,
                    ),
                ),
                ("season", models.TextField(blank=True, null=True)),
                ("season_year", models.IntegerField(blank=True, null=True)),
                ("episodes", models.IntegerField(blank=True, null=True)),
                ("duration_min", models.IntegerField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("cover_url", models.TextField(blank=True, null=True)),
                ("is_adult", models.BooleanField(default=False)),
                ("merge_hash", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "anime",
                "indexes": [
                    models.Index(fields=["status"], name="anime_status_390465_idx"),
                    models.Index(
                        fields=["season_year"], name="anime_season__365325_idx"
                    ),
                    models.Index(fields=["-popularity"], name="anime_popularity_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnimeRelation",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "anime_id",
                        "related_id",
                        "kind",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.TextField()),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.anime",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.anime",
                    ),
                ),
            ],
            options={
                "db_table": "anime_relation",
            },
        ),
        migrations.CreateModel(
            name="AnimeGenre",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "anime_id",
                        "genre_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.anime"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.genre"
                    ),
                ),
            ],
            options={
                "db_table": "anime_genre",
            },
        ),
        migrations.CreateModel(
            name="GenreLocalization",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "genre_id",
                        "locale",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "locale",
                    models.TextField(
                        choices=[
                            ("en", "en"),
                            ("ru", "ru"),
                            ("ja", "ja"),
                            ("ja_latn", "ja_latn"),
                        ]
                    ),
                ),
                ("name", models.TextField()),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localizations",
                        to="catalog.genre",
                    ),
                ),
            ],
            options={
                "db_table": "genre_localization",
            },
        ),
        migrations.CreateModel(
            name="AnimeStudio",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "anime_id",
                        "studio_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.anime"
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.studio"
                    ),
                ),
            ],
            options={
                "db_table": "anime_studio",
            },
        ),
        migrations.CreateModel(
            name="AnimeTag",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "anime_id",
                        "tag_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.SmallIntegerField()),
                ("is_spoiler", models.BooleanField(default=False)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.anime"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.tag"
                    ),
                ),
            ],
            options={
                "db_table": "anime_tag",
            },
        ),
        migrations.CreateModel(
            name="TagLocalization",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "tag_id",
                        "locale",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "locale",
                    models.TextField(
                        choices=[
                            ("en", "en"),
                            ("ru", "ru"),
                            ("ja", "ja"),
                            ("ja_latn", "ja_latn"),
                        ]
                    ),
                ),
                ("name", models.TextField()),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localizations",
                        to="catalog.tag",
                    ),
                ),
            ],
            options={
                "db_table": "tag_localization",
            },
        ),
        migrations.CreateModel(
            name="AnimeLocalization",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "anime_id",
                        "locale",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "locale",
                    models.TextField(
                        choices=[
                            ("en", "en"),
                            ("ru", "ru"),
                            ("ja", "ja"),
                            ("ja_latn", "ja_latn"),
                        ]
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("synopsis", models.TextField(blank=True, null=True)),
                ("title_source", models.TextField(blank=True, null=True)),
                ("synopsis_source", models.TextField(blank=True, null=True)),
                ("title_machine", models.BooleanField(default=False)),
                ("synopsis_machine", models.BooleanField(default=False)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localizations",
                        to="catalog.anime",
                    ),
                ),
            ],
            options={
                "db_table": "anime_localization",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("locale__in", ("en", "ru", "ja", "ja_latn"))
                        ),
                        name="anime_localization_locale_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnimeOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.TextField(
                        choices=[
                            ("title", "title"),
                            ("synopsis", "synopsis"),
                            ("format", "format"),
                            ("status", "status"),
                            ("season", "season"),
                            ("season_year", "season_year"),
                            ("episodes", "episodes"),
                            ("duration_min", "duration_min"),
                            ("score", "score"),
                            ("cover_url", "cover_url"),
                            ("is_adult", "is_adult"),
                            ("mal_id", "mal_id"),
                            ("shikimori_id", "shikimori_id"),
                            ("annict_id", "annict_id"),
                        ]
                    ),
                ),
                (
                    "locale",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("en", "en"),
                            ("ru", "ru"),
                            ("ja", "ja"),
                            ("ja_latn", "ja_latn"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="Empty value clears the field."
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("updated_by", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="catalog.anime",
                    ),
                ),
            ],
            options={
                "db_table": "anime_override",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anime", "field", "locale"),
                        name="anime_override_unique",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnimeSynonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                (
                    "locale",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("en", "en"),
                            ("ru", "ru"),
                            ("ja", "ja"),
                            ("ja_latn", "ja_latn"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonyms",
                        to="catalog.anime",
                    ),
                ),
            ],
            options={
                "db_table": "anime_synonym",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("anime", "value"), name="anime_synonym_unique"
                    )
                ],
            },
        ),
    ]
