# Generated by Django 5.2.17 on 2026-09-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.TextField(
                        choices=[
                            ("full", "Full"),
                            ("incremental", "Incremental"),
                            ("refresh", "Refresh"),
                            ("merge", "Merge"),
                            ("index", "Index"),
                            ("pools", "Pools"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="runs_ingest_status_f117ed_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunAnime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anilist_id", models.IntegerField()),
                ("anilist_changed", models.BooleanField(default=False)),
                ("written", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anime",
                        to="runs.ingestrun",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "anilist_id"), name="runanime_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunItemError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.TextField()),
                ("source", models.TextField(blank=True)),
                ("item_id", models.TextField(blank=True)),
                ("kind", models.TextField(default="error")),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_errors",
                        to="runs.ingestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["run", "stage"], name="runs_runite_run_id_780a1d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RunStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                    ),
                ),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="runs.ingestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "name"), name="runstage_run_name_unique"
                    )
                ],
            },
        ),
    ]
