# Generated by Django 5.2.17 on 2026-09-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdMapping",
            fields=[
                ("anilist_id", models.IntegerField(primary_key=True, serialize=False)),
                ("mal_id", models.IntegerField(blank=True, null=True)),
                ("mal_via", models.TextField(blank=True)),
                ("shikimori_id", models.TextField(blank=True, null=True)),
                ("annict_id", models.IntegerField(blank=True, null=True)),
                ("annict_via", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IdSourceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField()),
                ("anilist_id", models.IntegerField(blank=True, null=True)),
                ("mal_id", models.IntegerField(blank=True, null=True)),
                ("annict_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "anilist_id"],
                        name="pipeline_id_source_15945b_idx",
                    ),
                    models.Index(
                        fields=["source", "mal_id"],
                        name="pipeline_id_source_8c8f6a_idx",
                    ),
                ],
            },
        ),
    ]
