# Generated by Django 5.2.17 on 2026-09-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idmapping",
            name="annict_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idmapping",
            name="annict_searched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idmapping",
            name="mal_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idmapping",
            name="shikimori_searched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idmapping",
            name="shikimori_via",
            field=models.TextField(blank=True),
        ),
    ]
