"""contract/catalog-schema.sql: the catalog schema as other services see it."""

from __future__ import annotations

import os
import re
import subprocess
from typing import Any

from django.conf import settings

CONTRACT_PATH = settings.BASE_DIR / "contract" / "catalog-schema.sql"

HEADER = """-- Schema-only dump of schema `catalog`, owned by the ingest worker.
-- Generated by `manage.py dump_catalog_contract`; do not edit by hand.
-- The API and the rec engine load this file in their tests.
"""

# Lines that vary between pg_dump versions or runs, not with the schema.
_VOLATILE = re.compile(r"^(--.*|\\(un)?restrict .*|SET .*|SELECT pg_catalog\.set_config.*)$")


def dump_catalog_schema(db: dict[str, Any]) -> str:
    env = {**os.environ, "PGPASSWORD": str(db.get("PASSWORD") or "")}
    cmd = [
        "pg_dump",
        "--schema-only",
        "--schema=catalog",
        "--no-owner",
        "--no-privileges",
        "--exclude-table=catalog.django_migrations",
        "-h",
        str(db.get("HOST") or "localhost"),
        "-p",
        str(db.get("PORT") or 5432),
        "-U",
        str(db["USER"]),
        str(db["NAME"]),
    ]
    out = subprocess.run(cmd, check=True, capture_output=True, text=True, env=env).stdout
    return normalize(out)


def normalize(sql: str) -> str:
    lines = [line for line in sql.splitlines() if not _VOLATILE.match(line)]
    body = re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()
    return f"{HEADER}\n{body}\n"
